#encoding:utf-8

import os

DEBUG=True

SECRET_KEY=os.urandom(24)

# 数据库配置

HOSTNAME='120.26.106.222'
PORT='3306'
DATABASE='jijin'
USERNAME='julai01'
PASSWORD='Sh51785136@sh'
DB_URI='mysql+mysqldb://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI=DB_URI

SQLALCHEMY_TRACK_MODIFICATIONS = False
